backend:
  name: git-gateway
  branch: nieuwe-site

locale: nl

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "nieuws"
    label: "Nieuwsberichten"
    label_singular: "Bericht"
    folder: "nieuws/berichten"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Titel", widget: "string" }
      - { name: "date", label: "Datum", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD-MM-YYYY", time_format: false }
      - { name: "image", label: "Afbeelding", widget: "image", required: false }
      - { name: "excerpt", label: "Samenvatting", widget: "text" }
      - { name: "body", label: "Inhoud", widget: "markdown" }
